# Generated by Django 4.1.5 on 2023-01-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_URL', models.URLField(max_length=700)),
                ('Short_URL', models.CharField(max_length=100)),
                ('Time_Created', models.DateTimeField()),
            ],
        ),
    ]
